const configured=window.HAZZE_SUPABASE_URL?.startsWith('https://')&&window.HAZZE_SUPABASE_ANON_KEY?.length>20&&!window.HAZZE_SUPABASE_ANON_KEY.includes('PLAK_HIER');
const message=document.querySelector('#formMessage');
const form=document.querySelector('#updateForm');
const manageUpdates=document.querySelector('#manageUpdates');
const client=configured?window.supabase.createClient(window.HAZZE_SUPABASE_URL,window.HAZZE_SUPABASE_ANON_KEY):null;
function escapeHtml(value=''){const element=document.createElement('div');element.textContent=value;return element.innerHTML;}
function dateText(value){return value?new Intl.DateTimeFormat('nl-NL',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):'Geen tijd ingepland';}
async function loadUpdates(){const {data,error}=await client.from('actor_updates').select('id,title,category,scheduled_at,location,details,created_at').order('created_at',{ascending:false});if(error){manageUpdates.innerHTML='<div class="dashboard-item"><p class="muted">Updates konden niet geladen worden.</p></div>';return;}manageUpdates.innerHTML=data.length?data.map(update=>`<article class="dashboard-item"><span class="label">${escapeHtml(update.category)}</span><h3 style="margin-top:16px">${escapeHtml(update.title)}</h3><p class="muted">${escapeHtml(dateText(update.scheduled_at))}${update.location?` · ${escapeHtml(update.location)}`:''}</p><button class="delete-button" type="button" data-id="${update.id}" data-title="${escapeHtml(update.title)}">Melding verwijderen</button></article>`).join(''):'<div class="dashboard-item"><p class="muted">Er zijn nog geen updates.</p></div>';}
async function requireAdmin(){if(!client){message.textContent='Supabase is nog niet ingesteld.';form.hidden=true;return;}const {data:{session}}=await client.auth.getSession();if(!session){location.replace('acteurs.html');return;}const {data:isAdmin,error}=await client.rpc('is_actor_admin');if(error||!isAdmin){message.textContent='Je account heeft geen beheerdersrechten.';form.querySelectorAll('input, select, textarea, button').forEach(element=>element.disabled=true);return;}loadUpdates();}
form.addEventListener('submit',async event=>{event.preventDefault();if(!client)return;const button=form.querySelector('button');button.disabled=true;message.textContent='Update opslaan…';const scheduledAt=document.querySelector('#scheduledAt').value;const payload={title:document.querySelector('#title').value.trim(),category:document.querySelector('#category').value,scheduled_at:scheduledAt?new Date(scheduledAt).toISOString():null,location:document.querySelector('#location').value.trim()||null,details:document.querySelector('#details').value.trim()||null};const {error}=await client.from('actor_updates').insert(payload);button.disabled=false;if(error){message.textContent='Opslaan mislukt: '+error.message;return;}form.reset();message.textContent='✓ De update is geplaatst en staat nu in het castdashboard.';loadUpdates();});
manageUpdates.addEventListener('click',async event=>{const button=event.target.closest('.delete-button');if(!button||!client)return;if(!confirm(`Weet je zeker dat je “${button.dataset.title}” wilt verwijderen?`))return;button.disabled=true;const {error}=await client.from('actor_updates').delete().eq('id',button.dataset.id);if(error){message.textContent='Verwijderen mislukt: '+error.message;button.disabled=false;return;}message.textContent='✓ De melding is verwijderd.';loadUpdates();});
requireAdmin();
